// This file was dynamically generated.
// Do not edit this file directly.

exports.handleRequest = (req, res) => {
  // --- Response Configuration ---
  const statusCode = {{statusCode}};
  const headers = {{headers}};
  const body = {{body}};
  // --------------------------

  res.status(statusCode);

  // Set custom headers
  if (headers) {
    for (const [key, value] of Object.entries(headers)) {
      res.setHeader(key, value);
    }
  }

  // Send the response body
  // We check the content-type to decide how to send the response
  const contentType = (headers && (headers['Content-Type'] || headers['content-type'])) || 'application/json';

  if (contentType.includes('application/json')) {
    res.json(body);
  } else {
    res.send(String(body));
  }
};

