// This file was dynamically generated.
// Do not edit this file directly.

const express = require('express');
const router = express.Router();
const controller = require('{{controllerPath}}');

router.{{httpMethod}}('{{routePath}}', controller.handleRequest);

module.exports = router;

