<template><div class="go-doc min-h-screen bg-linear-to-br from-slate-50 to-blue-50"><header class="bg-white border-b border-slate-200"><div class="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between"><div><h1 class="text-2xl font-bold text-slate-800">粒子效果</h1><p class="text-sm text-slate-500 mt-1">GPUParticles2D / CPUParticles2D——火焰、烟雾、爆炸</p></div><div class="flex items-center gap-3"><span class="text-xs text-slate-400 bg-slate-100 px-3 py-1 rounded-full">阶段 2-12</span></div></div></header><main class="max-w-4xl mx-auto px-6 py-8 space-y-6"><Nav :list="navList" title="目录" position="top-right" :showBackToTop="true" />
<section id="sec-1" class="bg-white rounded-2xl shadow-md p-6 border border-slate-100"><h2 class="text-lg font-semibold text-slate-800 mb-4 flex items-center gap-2"><span class="w-8 h-8 bg-blue-100 text-blue-700 rounded-lg flex items-center justify-center text-sm">✨</span>概述</h2><aside class="bg-purple-50 border-l-4 border-purple-400 rounded-r-xl p-4 mb-4"><p class="text-sm text-purple-800"><strong>🔗 前端类比：</strong>粒子系统 ≈ <strong>CSS 粒子动画库（tsParticles / particles.js）</strong>——你用参数描述粒子的行为（生命周期、速度、颜色、大小），引擎自动模拟成百上千个粒子。</p></aside>
<div class="overflow-x-auto mb-4"><table class="w-full text-sm border-collapse"><tr class="bg-slate-100"><th class="px-4 py-2 border">节点</th><th class="px-4 py-2 border">说明</th></tr><tr><td class="px-4 py-2 border font-mono text-xs font-semibold">GPUParticles2D</td><td class="px-4 py-2 border"><strong>GPU 加速（推荐）</strong>——高性能，大量粒子用这个</td></tr><tr><td class="px-4 py-2 border font-mono text-xs">CPUParticles2D</td><td class="px-4 py-2 border">CPU 计算——兼容性好，少量粒子或老设备</td></tr></tbody></table></div>
<div class="mb-4"><Code language="gdscript" :code="particleCode" title="particles2d.gd" /></div></section>
<section id="sec-2" class="bg-white rounded-2xl shadow-md p-6 border border-slate-100"><h2 class="text-lg font-semibold text-slate-800 mb-4 flex items-center gap-2"><span class="w-8 h-8 bg-blue-100 text-blue-700 rounded-lg flex items-center justify-center text-sm">⚙️</span>关键属性（Inspector 中设置）</h2><div class="overflow-x-auto mb-4"><table class="w-full text-sm border-collapse"><tr class="bg-slate-100"><th class="px-4 py-2 border">属性</th><th class="px-4 py-2 border">说明</th></tr><tr><td class="px-4 py-2 border font-mono text-xs">amount</td><td class="px-4 py-2 border">粒子数量</td></tr><tr><td class="px-4 py-2 border font-mono text-xs">lifetime</td><td class="px-4 py-2 border">粒子存活时间（秒）</td></tr><tr><td class="px-4 py-2 border font-mono text-xs">process_material</td><td class="px-4 py-2 border"><strong>粒子材质</strong>——控制速度/颜色/大小/旋转等所有行为</td></tr><tr><td class="px-4 py-2 border font-mono text-xs">texture</td><td class="px-4 py-2 border">粒子纹理（单张图）</td></tr><tr><td class="px-4 py-2 border font-mono text-xs">one_shot</td><td class="px-4 py-2 border">true=爆炸（一次发射完），false=持续发射</td></tr><tr><td class="px-4 py-2 border font-mono text-xs">explosiveness</td><td class="px-4 py-2 border">0=持续发射，1=瞬间全部发射（爆炸）</td></tr></tbody></table></div>
<aside class="bg-emerald-50 border-l-4 border-emerald-400 rounded-r-xl p-4"><p class="text-sm text-emerald-800"><strong>✅ 推荐工作流：</strong>在编辑器中视觉调试粒子参数（所见即所得），代码中只控制 <code class="bg-emerald-100 px-1 rounded text-xs font-mono">emitting</code> 开关和 <code class="bg-emerald-100 px-1 rounded text-xs font-mono">one_shot</code> 触发。</p></aside></section></main>
<footer class="max-w-4xl mx-auto px-6 py-8"><nav class="flex justify-between items-center pt-4 border-t border-slate-200 text-sm"><RouterLink to="/GameProduction/GotDot/godot-stage-2-node-system/godot-2-11-audiostream" class="text-slate-500 hover:text-blue-600 flex items-center gap-1">← 上一节：AudioStream</RouterLink><span class="text-slate-300">阶段 2 完成！下一阶段：UI 系统 →</span></nav></footer></div></template>
<script setup lang="ts">import { Code, Nav } from 'components'; import { RouterLink } from 'vue-router'
const navList = [{id:"sec-1",name:"概述"},{id:"sec-2",name:"关键属性"}]
const particleCode = `# GPUParticles2D ——代码控制粒子效果
@onready var particles: GPUParticles2D = $GPUParticles2D
func _ready() -> void:
    particles.emitting = false  # 默认不发射
func explode() -> void:
    particles.emitting = true   # 开始发射（one_shot=true 时一次性）
func start_continuous() -> void:
    particles.emitting = true   # 持续发射（one_shot=false）`
</script>
