<template>
  <div class="go-doc min-h-screen bg-linear-to-br from-slate-50 to-blue-50">
    <header class="bg-white border-b border-slate-200"><div class="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between"><div><h1 class="text-2xl font-bold text-slate-800">Godot vs Unity vs Unreal</h1><p class="text-sm text-slate-500 mt-1">三选一——独立游戏开发者视角的客观对比</p></div><div class="flex items-center gap-3"><span class="text-xs text-slate-400 bg-slate-100 px-3 py-1 rounded-full">阶段 0-6</span></div></div></header>
    <main class="max-w-4xl mx-auto px-6 py-8 space-y-6"><Nav :list="navList" title="目录" position="top-right" :showBackToTop="true" />

      <section id="sec-1" class="bg-white rounded-2xl shadow-md p-6 border border-slate-100"><h2 class="text-lg font-semibold text-slate-800 mb-4 flex items-center gap-2"><span class="w-8 h-8 bg-blue-100 text-blue-700 rounded-lg flex items-center justify-center text-sm">⚖️</span>概述</h2>
        <aside class="bg-purple-50 border-l-4 border-purple-400 rounded-r-xl p-4 mb-4"><p class="text-sm text-purple-800"><strong>🔗 前端类比：</strong>选引擎 ≈ 选前端框架——<strong>Godot ≈ Vue/Svelte</strong>（轻量、社区驱动、上手快），<strong>Unity ≈ React</strong>（生态最大、企业支持、中等复杂度），<strong>Unreal ≈ Angular</strong>（企业级、功能全、学习曲线陡）。没有绝对的好坏，只有<strong>适不适合你的项目</strong>。</p></aside>
        <p class="text-slate-600 leading-relaxed">作为一个要<strong>独立开发游戏</strong>的程序员，你的核心需求是：低成本（免费）、快速迭代（轻量编辑器）、2D 优先、Git 友好、能用熟悉的编程范式。以下从这几个维度逐一对比。</p>
      </section>

      <section id="sec-2" class="bg-white rounded-2xl shadow-md p-6 border border-slate-100"><h2 class="text-lg font-semibold text-slate-800 mb-4 flex items-center gap-2"><span class="w-8 h-8 bg-blue-100 text-blue-700 rounded-lg flex items-center justify-center text-sm">1</span>核心对比总表</h2>
        <div class="overflow-x-auto mb-4"><table class="w-full text-sm border-collapse"><thead><tr class="bg-slate-100 text-left"><th class="px-4 py-2 border border-slate-200 font-semibold text-slate-700">维度</th><th class="px-4 py-2 border border-slate-200 font-semibold text-slate-700">Godot 4.x</th><th class="px-4 py-2 border border-slate-200 font-semibold text-slate-700">Unity 6</th><th class="px-4 py-2 border border-slate-200 font-semibold text-slate-700">Unreal 5</th></tr></thead><tbody class="text-slate-600">
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">价格</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">完全免费</span>（MIT 协议，无抽成）</td><td class="px-4 py-2 border border-slate-200">Personal 免费（年收入<$200K）；Pro $2,040/年/席</td><td class="px-4 py-2 border border-slate-200">免费使用；收入超 $1M 后 <strong>5% 版税</strong></td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">编辑器体积</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">~50MB</span></td><td class="px-4 py-2 border border-slate-200">~5GB+</td><td class="px-4 py-2 border border-slate-200">~40GB+</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">启动速度</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">2-5 秒</span></td><td class="px-4 py-2 border border-slate-200">30-60 秒</td><td class="px-4 py-2 border border-slate-200">1-3 分钟</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">2D 游戏</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">⭐⭐⭐⭐⭐</span> 原生 2D 引擎，像素完美</td><td class="px-4 py-2 border border-slate-200">⭐⭐⭐ 2D 是 3D 的降维模式</td><td class="px-4 py-2 border border-slate-200">⭐⭐ Paper2D（已废弃），不推荐 2D</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">3D 游戏</td><td class="px-4 py-2 border border-slate-200">⭐⭐⭐ 4.x 大幅提升，够用但不够 AAA</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">⭐⭐⭐⭐</span> HDRP/URP 成熟</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">⭐⭐⭐⭐⭐</span> Nanite/Lumen 顶流</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">脚本语言</td><td class="px-4 py-2 border border-slate-200">GDScript（类 Python）+ C#</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">C#</span>（唯一脚本语言）</td><td class="px-4 py-2 border border-slate-200">C++ + <span class="text-emerald-600 font-semibold">Blueprint</span>（可视化编程）</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">学习曲线</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">⭐⭐ 低</span>（GDScript 易上手）</td><td class="px-4 py-2 border border-slate-200">⭐⭐⭐ 中等</td><td class="px-4 py-2 border border-slate-200">⭐⭐⭐⭐ 高（C++ 门槛）</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">开源</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">✅ 完全开源</span>（MIT）</td><td class="px-4 py-2 border border-slate-200">❌ 闭源</td><td class="px-4 py-2 border border-slate-200">⚠️ 源码可看、不可分发</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">Git 友好</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">✅ .tscn 纯文本</span></td><td class="px-4 py-2 border border-slate-200">⚠️ 场景二进制 + YAML 合并工具</td><td class="px-4 py-2 border border-slate-200">❌ 大型二进制，基本不能 diff</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">Asset Store</td><td class="px-4 py-2 border border-slate-200">⚠️ 生态较小但增长快</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">✅ 最大最成熟</span></td><td class="px-4 py-2 border border-slate-200">✅ Quixel Megascans 免费</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">导出平台</td><td class="px-4 py-2 border border-slate-200">Win/Mac/Linux/<span class="text-emerald-600 font-semibold">Web</span>/Android/iOS</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">25+ 平台</span>（最广）</td><td class="px-4 py-2 border border-slate-200">Win/Mac/Linux/Console/手机</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">适合谁</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600 font-semibold">独立开发者/2D/小团队</span></td><td class="px-4 py-2 border border-slate-200">中型团队/手游/跨平台</td><td class="px-4 py-2 border border-slate-200">AAA 工作室/3D 大作</td></tr>
        </tbody></table></div>
      </section>

      <section id="sec-3" class="bg-white rounded-2xl shadow-md p-6 border border-slate-100"><h2 class="text-lg font-semibold text-slate-800 mb-4 flex items-center gap-2"><span class="w-8 h-8 bg-blue-100 text-blue-700 rounded-lg flex items-center justify-center text-sm">2</span>价格——最实在的区别</h2>
        <p class="text-slate-600 mb-3 leading-relaxed"><strong>这是独立开发者最重要的考量。</strong></p>
        <ul class="space-y-2 text-slate-600 text-sm mb-4"><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>Godot：免费，零版税。</strong>你的游戏卖 $1,000,000 → 你拿到 $1,000,000。MIT 协议允许你修改引擎源码并发布。</span></li><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>Unity：</strong>Personal 版免费（年收入<$200K）。2023 年的 Runtime Fee 风波（按安装次数收费）后虽已撤回，但<strong>信任已受损</strong>。</span></li><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>Unreal：</strong>引擎免费，但你的游戏总收入超过 <strong>$1,000,000</strong> 后，超出部分收 <strong>5%</strong> 版税。Epic 对每季度前 $1M 免版税。</span></li></ul>
        <aside class="bg-amber-50 border-l-4 border-amber-400 rounded-r-xl p-4"><p class="text-sm text-amber-800"><strong>⚠️ 投资视角：</strong>如果你相信自己能做出收入 $200K+ 的游戏，Unity 的 Pro 年费（$2,040）不算什么。但如果你刚开始做独立游戏、不确定能否盈利，<strong>Godot 的零风险</strong>是最佳选择。</p></aside>
      </section>

      <section id="sec-4" class="bg-white rounded-2xl shadow-md p-6 border border-slate-100"><h2 class="text-lg font-semibold text-slate-800 mb-4 flex items-center gap-2"><span class="w-8 h-8 bg-blue-100 text-blue-700 rounded-lg flex items-center justify-center text-sm">3</span>2D 游戏——Godot 的最强项</h2>
        <p class="text-slate-600 mb-3 leading-relaxed">如果你要做<strong>2D 独立游戏</strong>（像素风、平台跳跃、银河恶魔城、Roguelike），Godot 是目前最好的选择：</p>
        <ul class="space-y-2 text-slate-600 text-sm mb-4"><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>原生 2D 引擎：</strong>Godot 的 2D 渲染器从底层就是为像素和 2D 坐标设计的。不像 Unity 的 2D 本质是 3D 场景的"平面模式"。</span></li><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>像素完美：</strong>Godot 默认就是 Nearest 过滤 + 像素对齐。Unity 需要手动配置一堆设置才能达到同样效果。</span></li><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>TileMap：</strong>Godot 4.x 的 TileMap 系统支持自动拼接（terrain autotiling）、多层、动画瓦片。Unity 的 Tilemap 功能类似但更繁琐。</span></li><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>2D 物理：</strong>Godot 的 2D 物理（CharacterBody2D、Area2D、RayCast2D）设计直觉、API 清晰。Unity 的 2D 物理 API 是 3D 物理的"镜像"。</span></li></ul>
        <aside class="bg-emerald-50 border-l-4 border-emerald-400 rounded-r-xl p-4"><p class="text-sm text-emerald-800"><strong>✅ 结论：</strong>2D 独立游戏 → Godot。3D AAA 大作 → Unreal。介于两者之间 → Unity。对于你（独立开发者，2D 为主），Godot 是最优解。</p></aside>
      </section>

      <section id="sec-5" class="bg-white rounded-2xl shadow-md p-6 border border-slate-100"><h2 class="text-lg font-semibold text-slate-800 mb-4 flex items-center gap-2"><span class="w-8 h-8 bg-blue-100 text-blue-700 rounded-lg flex items-center justify-center text-sm">4</span>程序员视角的脚本语言对比</h2>
        <div class="overflow-x-auto mb-4"><table class="w-full text-sm border-collapse"><thead><tr class="bg-slate-100 text-left"><th class="px-4 py-2 border border-slate-200 font-semibold text-slate-700">特性</th><th class="px-4 py-2 border border-slate-200 font-semibold text-slate-700">GDScript (Godot)</th><th class="px-4 py-2 border border-slate-200 font-semibold text-slate-700">C# (Unity)</th><th class="px-4 py-2 border border-slate-200 font-semibold text-slate-700">Blueprint (Unreal)</th></tr></thead><tbody class="text-slate-600">
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">语法风格</td><td class="px-4 py-2 border border-slate-200">Python-like（缩进、无分号）</td><td class="px-4 py-2 border border-slate-200">C 风格（花括号、分号）</td><td class="px-4 py-2 border border-slate-200">可视化节点连线</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">类型系统</td><td class="px-4 py-2 border border-slate-200">动态 + 可选静态标注</td><td class="px-4 py-2 border border-slate-200">强静态类型</td><td class="px-4 py-2 border border-slate-200">强类型节点</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">学习成本</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600">低</span>（Python 或 TS 开发者 1 天上手）</td><td class="px-4 py-2 border border-slate-200">中（C# 本身较复杂）</td><td class="px-4 py-2 border border-slate-200">低（可视化）但 C++ 很高</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">与引擎集成</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600">极紧密</span>（专为 Godot 设计）</td><td class="px-4 py-2 border border-slate-200">紧密</td><td class="px-4 py-2 border border-slate-200">紧密（但 BP 有性能开销）</td></tr>
          <tr><td class="px-4 py-2 border border-slate-200 font-medium">你的优势</td><td class="px-4 py-2 border border-slate-200"><span class="text-emerald-600">TS 类型注解 + Python 语法</span> = 已掌握 80%</td><td class="px-4 py-2 border border-slate-200">TS 类型系统相似，但需学 C# 生态</td><td class="px-4 py-2 border border-slate-200">几乎全新，C++ 是另一座山</td></tr>
        </tbody></table></div>
      </section>

      <section id="sec-6" class="bg-white rounded-2xl shadow-md p-6 border border-slate-100"><h2 class="text-lg font-semibold text-slate-800 mb-4 flex items-center gap-2"><span class="w-8 h-8 bg-blue-100 text-blue-700 rounded-lg flex items-center justify-center text-sm">5</span>什么时候可能换引擎？</h2>
        <p class="text-slate-600 mb-3 leading-relaxed">诚实地说，以下场景你可能需要离开 Godot：</p>
        <ul class="space-y-2 text-slate-600 text-sm mb-4"><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>做 3A 级 3D 游戏：</strong>Godot 4.x 的 3D 进步很大，但离 Unreal 的 Nanite/Lumen 还有距离。做写实 3D 大作选 Unreal。</span></li><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>需要用到大量 Unity Asset Store 资源：</strong>Unity 的生态目前最大。如果你严重依赖第三方插件和资源，Unity 更省事。</span></li><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>找游戏开发工作：</strong>目前招聘市场上 Unity 的岗位远多于 Godot。但从趋势看，Godot 在独立游戏领域的份额在快速增长。</span></li><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>Switch/PlayStation 主机发布：</strong>Godot 的主机导出需要第三方公司（如 Lone Wolf Technology）的移植服务。Unity/Unreal 原生支持。</span></li></ul>
        <aside class="bg-emerald-50 border-l-4 border-emerald-400 rounded-r-xl p-4"><p class="text-sm text-emerald-800"><strong>✅ 对于你的情况（独立 2D 游戏、Git 工作流、TS/Python 背景）：</strong>Godot 是目前最合适的选择。你不需要 Unity 的庞大生态，也不需要 Unreal 的电影级渲染。Godot 的轻量、开放和代码友好性正对你的需求。</p></aside>
      </section>

      <section id="sec-7" class="bg-white rounded-2xl shadow-md p-6 border border-slate-100"><h2 class="text-lg font-semibold text-slate-800 mb-4 flex items-center gap-2"><span class="w-8 h-8 bg-blue-100 text-blue-700 rounded-lg flex items-center justify-center text-sm">📋</span>小结</h2>
        <ul class="space-y-2 text-slate-600"><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>Godot ≈ Vue</strong>（轻量、开源、上手快、2D 最强）→ 独立游戏 / 2D / 快速原型</span></li><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>Unity ≈ React</strong>（生态最大、企业支持、学习曲线中等）→ 中型团队 / 手游</span></li><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span><strong>Unreal ≈ Angular</strong>（功能全、学习曲线陡、3D 王者）→ AAA 3D 大作</span></li><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span>你的背景（TS/Python/Git/2D 独立游戏）→ <strong>Godot 是最优解</strong></span></li><li class="flex items-start gap-2"><span class="text-blue-500 mt-1">▸</span><span>MIT 协议：免费、无抽成、可改源码——独立开发者最关心的商业安全</span></li></ul>
      </section>
    </main>
    <footer class="max-w-4xl mx-auto px-6 py-8"><nav class="flex justify-between items-center pt-4 border-t border-slate-200 text-sm"><RouterLink to="/GameProduction/GotDot/godot-stage-0-overview/godot-0-5-first-project" class="text-slate-500 hover:text-blue-600 transition-colors flex items-center gap-1">← 上一节：第一个项目：Hello Godot</RouterLink><RouterLink to="/GameProduction/GotDot/godot-stage-1-gdscript-basics/godot-1-1-gdscript-intro" class="text-blue-600 hover:text-blue-700 font-medium transition-colors flex items-center gap-1">下一节：GDScript 简介与设计哲学 →</RouterLink></nav></footer>
  </div>
</template>

<script setup lang="ts">
import { Nav } from 'components'; import { RouterLink } from 'vue-router'
const navList = [{id:"sec-1",name:"概述"},{id:"sec-2",name:"核心对比总表"},{id:"sec-3",name:"价格对比"},{id:"sec-4",name:"2D 游戏"},{id:"sec-5",name:"脚本语言对比"},{id:"sec-6",name:"何时换引擎"},{id:"sec-7",name:"小结"}]
</script>
